<?xml version="1.0"?>
<package format="3">
  <name>telemetry_system</name>
  <version>0.0.0</version>
  <description>ROS2 telemetry publisher and bridge</description>
  <maintainer email="dave@example.com">dave</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3-flask</exec_depend>

  <buildtool_depend>ament_python</buildtool_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>